In [1]:
import pandas as pd

In [4]:
df = pd.read_csv("covid_toy.csv")  # Corrected 'read_csv' to 'pd.read_csv'

In [ ]:
# How can we check the first few rows of the DataFrame?
df.head()  # Display the first 5 rows of the DataFrame
# df.head(10)  # Display the first 10 rows of the DataFrame

In [11]:
# How can we check the last few rows of the DataFrame?
df.tail()  # Display the last 5 rows of the DataFrame
# df.tail(10)  # Display the last 10 rows of the DataFrame

    age  gender  fever   cough       city has_covid
95   12  Female  104.0    Mild  Bangalore        No
96   51  Female  101.0  Strong    Kolkata       Yes
97   20  Female  101.0    Mild  Bangalore        No
98    5  Female   98.0  Strong     Mumbai        No
99   10  Female   98.0  Strong    Kolkata       Yes

In [18]:
df.sample(5)  # Randomly sample 5 rows from the DataFrame

    age  gender  fever   cough     city has_covid
23   80  Female   98.0    Mild    Delhi       Yes
29   34  Female    NaN  Strong   Mumbai       Yes
4    65  Female  101.0    Mild   Mumbai        No
79   48  Female  103.0    Mild  Kolkata       Yes
11   65  Female   98.0    Mild   Mumbai       Yes

In [17]:
print(df.shape)  # Get the shape of the DataFrame (number of rows, number of columns)

print(df.columns)  # Get the column names of the DataFrame

(100, 6)
Index(['age', 'gender', 'fever', 'cough', 'city', 'has_covid'], dtype='object')

In [ ]:
print(df.info())  # Get a concise summary of the DataFrame

df.describe()  # Get descriptive statistics of the DataFrame

In [ ]:
# DataFrame is mutable
df ['gender'][0] = 'Female'  # Corrected syntax error by adding closing quote
df.head()  # Display the first 5 rows of the DataFrame after modification

In [ ]:
# loc() and iloc() methods
# df.loc[row_range, column_name] for label-based indexing ----> last index value will be included
# df.iloc[row_range, column_index] for positional indexing ----> last index value will be excluded
df.loc[0]  # Access the first row using loc
df.iloc[0]  # Access the first row using iloc

In [ ]:
df.loc[0:2]  # Access the first two rows using loc (inclusive of last index)
df.iloc[0:2]  # Access the first two rows using iloc (exclusive of last index)

df.loc[2:5, ['age', 'gender', 'had_covid']]  # Access rows 2 to 5 and specific columns using loc
df.iloc[2:5, [0, 1, 3]]  # Access rows 2 to 5 and specific columns using iloc (using column indices

In [ ]:
# if you want to check total sub-categories frequency of a column then we use 
# pd.value_counts()
df['had_covid'].value_counts()  # Get the frequency of each unique value in the 'had_covid' column
df['cough'].value_counts()  # Get the frequency of each unique value in the 'cough' column
df['city'].value_counts()  # Get the frequency of each unique value in the 'city' column
df['gender'].value_counts()  # Get the frequency of each unique value
# if you want to check total sub-categories frequency of a column then we use 
# pd.value_counts()

In [ ]:
# how can we check missing values in the DataFrame?
df.isnull().sum()  # Check for missing values in each column and sum them up
a = df 
a = a.dropna()  # Drop rows with any missing values
a.isnull().sum()  # Check for missing values again after dropping rows
a.shape

In [ ]:
# How can we fill the missing values in the DataFrame?
#  df['column_name'] ----> Numerical ----> column mean fill
# df['column_name'].fillna(value, inplace=True)  # Fill missing values in a specific colum

# df['col'] ----> Categorical ----> column mode fill

In [ ]:
df['fever'] = df['fever'].fillna(df['fever'].mean())  # Fill missing values in 'fever' column with mean
df.shape
df['has_covid'].mode()
df['has_covid'].value_counts()

In [19]:
df

    age  gender  fever   cough       city has_covid
0    60    Male  103.0    Mild    Kolkata        No
1    27    Male  100.0    Mild      Delhi       Yes
2    42    Male  101.0    Mild      Delhi        No
3    31  Female   98.0    Mild    Kolkata        No
4    65  Female  101.0    Mild     Mumbai        No
..  ...     ...    ...     ...        ...       ...
95   12  Female  104.0    Mild  Bangalore        No
96   51  Female  101.0  Strong    Kolkata       Yes
97   20  Female  101.0    Mild  Bangalore        No
98    5  Female   98.0  Strong     Mumbai        No
99   10  Female   98.0  Strong    Kolkata       Yes

[100 rows x 6 columns]