
# Pandas `.loc` and `.iloc` Explained

This notebook explains:

- What `.loc` is
- What `.iloc` is
- Differences between them
- Common real-world usage patterns
- Important edge cases

In [34]:

import pandas as pd

df = pd.DataFrame({
    "Name": ["Alice", "Bob", "Charlie"],
    "Age": [25, 30, 35],
    "City": ["Delhi", "Mumbai", "Pune"]
}, index=["a", "b", "c"])

df

      Name  Age    City
a    Alice   25   Delhi
b      Bob   30  Mumbai
c  Charlie   35    Pune


## `.loc` — Label Based Selection

`.loc` works with:

- Row labels
- Column labels

In [6]:

# Single row
df.loc["a"]

Name    Alice
Age        25
City    Delhi
Name: a, dtype: object

In [3]:

# Single value
df.loc["b", "Age"]

np.int64(30)

In [4]:

# Multiple rows
df.loc[["a", "c"]]

      Name  Age   City
a    Alice   25  Delhi
c  Charlie   35   Pune

In [ ]:

# Multiple rows and columns
df.loc[["a", "b"], ["Name", "Age"]]

In [ ]:

# Slicing with .loc (end INCLUDED)
df.loc["a":"c"]


## `.iloc` — Integer Position Based Selection

`.iloc` works with integer positions.

Row positions:

- a → 0
- b → 1
- c → 2

In [7]:

# Single row
df.iloc[0]

Name    Alice
Age        25
City    Delhi
Name: a, dtype: object

In [8]:

# Single value
df.iloc[1, 1]

np.int64(30)

In [12]:

# Multiple rows and columns
df.iloc[[0, 2], [0, 2]]

      Name   City
a    Alice  Delhi
c  Charlie   Pune

In [ ]:

# Slicing with .iloc (end EXCLUDED)
df.iloc[0:2] # slicing rows

    Name  Age    City
a  Alice   25   Delhi
b    Bob   30  Mumbai

In [ ]:
df.iloc[0:2, 0:2] # slicing rows and columns together

    Name  Age
a  Alice   25
b    Bob   30

In [31]:
df.iloc[:, 0:2] # slicing columns for all rows

      Name  Age
a    Alice   25
b      Bob   30
c  Charlie   35

In [ ]:
# when you need specific columns
df.iloc[0:2].loc[:, ["Name", "City"]]

    Name    City
a  Alice   Delhi
b    Bob  Mumbai

In [28]:
df.iloc[0:2].iloc[:, [0, 2]]

    Name    City
a  Alice   Delhi
b    Bob  Mumbai


## Boolean Filtering with `.loc`

Very common in real-world data analysis.

In [ ]:

df.loc[df["Age"] > 25]

In [ ]:

df.loc[df["Age"] > 25, ["Name", "City"]]


## Setting Values

In [35]:
df

      Name  Age    City
a    Alice   25   Delhi
b      Bob   30  Mumbai
c  Charlie   35    Pune

In [36]:

# Using .loc
df.loc["a", "Age"] = 26

# Using .iloc
df.iloc[1, 1] = 31

df

      Name  Age    City
a    Alice   26   Delhi
b      Bob   31  Mumbai
c  Charlie   35    Pune


## Integer Index Confusion

One of the most important edge cases.

In [37]:

df2 = pd.DataFrame(
    {"A": [10, 20, 30]},
    index=[100, 101, 102]
)

df2

      A
100  10
101  20
102  30

In [38]:

# Label-based
df2.loc[100]

A    10
Name: 100, dtype: int64

In [40]:

# Position-based
df2.iloc[0]

A    10
Name: 100, dtype: int64


## Negative Indexing

In [41]:

# Last row using iloc
df.iloc[-1]

Name    Charlie
Age          35
City       Pune
Name: c, dtype: object


`.loc[-1]` only works if `-1` exists as an actual index label.


## Common Industry Usage Patterns

In [ ]:

# Filtering rows
df.loc[df["Age"] > 25]

# Selecting columns
df.loc[:, ["Name", "Age"]]

# First column by position
df.iloc[:, 0]

# First 2 rows
df.iloc[:2]


# Quick Summary

| Feature | `.loc` | `.iloc` |
|---|---|---|
| Based on | labels | positions |
| Uses names | Yes | No |
| Slice end included | Yes | No |
| Negative indexing | label-based | positional |
| Common for filtering | Yes | Less common |

## Mental Model

```python
.loc[label]
.iloc[position]
```