### **19 More Important Functions**

1. value_counts
2. sort_values
3. rank
4. sort_index
5. set_index
6. rename_index -> rename
7. reset_index
8. unique & nunique
9. isnull/notnull/hasnans
10. dropna
11. fillna
12. drop_duplicates
13. drop
14. apply
15. isin
16. corr
17. nlargest -> nsmallest
18. insert
19. copy

In [127]:
import numpy as np
import pandas as pd

In [128]:
# sample dataframe
marks = pd.DataFrame([
    [100,80,10],
    [90,70,7],
    [120,100,14],
    [80,70,14],
    [80,70,14]
],columns=['iq','marks','package'])

marks

    iq  marks  package
0  100     80       10
1   90     70        7
2  120    100       14
3   80     70       14
4   80     70       14

# **1. value_counts() --->(series & dataframe)**

In [129]:
# Value counts of a series
a = pd.Series([1,1,1,2,2,3])
a.value_counts()

1    3
2    2
3    1
Name: count, dtype: int64

In [130]:
# Value counts of a dataframe
marks.value_counts()

iq   marks  package
80   70     14         2
90   70     7          1
100  80     10         1
120  100    14         1
Name: count, dtype: int64

- Find which player has won most potm -> in finals and qualifiers

In [131]:
ipl = pd.read_csv('../04CampusX_DataSet/datasets-session-17/ipl-matches.csv')
ipl[~ipl['MatchNumber'].str.isdigit()]['Player_of_Match'].value_counts().head(10)

Player_of_Match
F du Plessis      3
SK Raina          3
KA Pollard        3
JJ Bumrah         2
AB de Villiers    2
MK Pandey         2
M Vijay           2
A Kumble          2
YK Pathan         2
SR Watson         2
Name: count, dtype: int64

- Toss decision plot

In [132]:
# ipl['TossDecision'].value_counts().plot(kind='pie')

- How many matches each team has played

In [133]:
(ipl['Team2'].value_counts() + ipl['Team1'].value_counts()).sort_values(ascending=False)

Mumbai Indians                 231
Royal Challengers Bangalore    226
Kolkata Knight Riders          223
Chennai Super Kings            208
Rajasthan Royals               192
Kings XI Punjab                190
Delhi Daredevils               161
Sunrisers Hyderabad            152
Deccan Chargers                 75
Delhi Capitals                  63
Pune Warriors                   46
Gujarat Lions                   30
Punjab Kings                    28
Gujarat Titans                  16
Rising Pune Supergiant          16
Lucknow Super Giants            15
Kochi Tuskers Kerala            14
Rising Pune Supergiants         14
Name: count, dtype: int64

# **2. sort_values() --->(series & dataframe)**
-> ascending 
-> na_position 
-> inplace 
-> multiple cols

In [134]:
# Sample series for sort_values
x = pd.Series([12,14,1,56,89])
x.sort_values(ascending=False)

4    89
3    56
1    14
0    12
2     1
dtype: int64

In [135]:
movies = pd.read_csv('../04CampusX_DataSet/datasets-session-17/movies.csv')
# movies.head(4)

In [136]:
movies.sort_values('title_x',ascending=False).head(2)

,title_x,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date
1623,Zubeidaa,tt0255713,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Zubeidaa,Zubeidaa,Zubeidaa,0,2001,153,Biography|Drama|History,6.2,1384,The film begins with Riyaz (Rajat Kapoor) Zub...,Zubeidaa an aspiring Muslim actress marries ...,The Story of a Princess,Karisma Kapoor|Rekha|Manoj Bajpayee|Rajit Kapo...,3 wins & 13 nominations,19 January 2001 (India)
939,Zor Lagaa Ke...Haiya!,tt1479857,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Zor_Lagaa_Ke...H...,Zor Lagaa Ke... Haiya!,Zor Lagaa Ke... Haiya!,0,2009,\N,Comedy|Drama|Family,6.4,46,A tree narrates the story of four Mumbai-based...,Children build a tree-house to spy on a beggar...,NaN,Meghan Jadhav|Mithun Chakraborty|Riya Sen|Seem...,NaN,NaN

In [137]:
# Sample dataframe for sort_values
students = pd.DataFrame(
    {
        'name':['nitish','ankit','rupesh',np.nan,'mrityunjay',np.nan,'rishabh',np.nan,'aditya',np.nan],
        'college':['bit','iit','vit',np.nan,np.nan,'vlsi','ssit',np.nan,np.nan,'git'],
        'branch':['eee','it','cse',np.nan,'me','ce','civ','cse','bio',np.nan],
        'cgpa':[6.66,8.25,6.41,np.nan,5.6,9.0,7.4,10,7.4,np.nan],
        'package':[4,5,6,np.nan,6,7,8,9,np.nan,np.nan]

    }
)

students

         name college branch   cgpa  package
0      nitish     bit    eee   6.66      4.0
1       ankit     iit     it   8.25      5.0
2      rupesh     vit    cse   6.41      6.0
3         NaN     NaN    NaN    NaN      NaN
4  mrityunjay     NaN     me   5.60      6.0
5         NaN    vlsi     ce   9.00      7.0
6     rishabh    ssit    civ   7.40      8.0
7         NaN     NaN    cse  10.00      9.0
8      aditya     NaN    bio   7.40      NaN
9         NaN     git    NaN    NaN      NaN

In [138]:
# na_position to place the null values at the beginning of the dataframe
students.sort_values('name',na_position='first',ascending=True)

# na_position to place the null values at the end of the dataframe
students.sort_values('name',na_position='last',ascending=True)

         name college branch   cgpa  package
8      aditya     NaN    bio   7.40      NaN
1       ankit     iit     it   8.25      5.0
4  mrityunjay     NaN     me   5.60      6.0
0      nitish     bit    eee   6.66      4.0
6     rishabh    ssit    civ   7.40      8.0
2      rupesh     vit    cse   6.41      6.0
3         NaN     NaN    NaN    NaN      NaN
5         NaN    vlsi     ce   9.00      7.0
7         NaN     NaN    cse  10.00      9.0
9         NaN     git    NaN    NaN      NaN

In [139]:
# Using inplace to make permanent changes to the dataframe
students.sort_values('name',na_position='first',ascending=True,inplace=True)

In [140]:
students

         name college branch   cgpa  package
3         NaN     NaN    NaN    NaN      NaN
5         NaN    vlsi     ce   9.00      7.0
7         NaN     NaN    cse  10.00      9.0
9         NaN     git    NaN    NaN      NaN
8      aditya     NaN    bio   7.40      NaN
1       ankit     iit     it   8.25      5.0
4  mrityunjay     NaN     me   5.60      6.0
0      nitish     bit    eee   6.66      4.0
6     rishabh    ssit    civ   7.40      8.0
2      rupesh     vit    cse   6.41      6.0

In [141]:
# Sorting the dataframe on multiple columns
movies.sort_values(['year_of_release','title_x'],ascending=[True,False]).head(2)

,title_x,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date
1623,Zubeidaa,tt0255713,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Zubeidaa,Zubeidaa,Zubeidaa,0,2001,153,Biography|Drama|History,6.2,1384,The film begins with Riyaz (Rajat Kapoor) Zub...,Zubeidaa an aspiring Muslim actress marries ...,The Story of a Princess,Karisma Kapoor|Rekha|Manoj Bajpayee|Rajit Kapo...,3 wins & 13 nominations,19 January 2001 (India)
1625,Yeh Zindagi Ka Safar,tt0298607,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Yeh_Zindagi_Ka_S...,Yeh Zindagi Ka Safar,Yeh Zindagi Ka Safar,0,2001,146,Drama,3.0,133,Hindi pop-star Sarina Devan lives a wealthy ...,A singer finds out she was adopted when the ed...,NaN,Ameesha Patel|Jimmy Sheirgill|Nafisa Ali|Gulsh...,NaN,16 November 2001 (India)

# **3. Rank ---> (Series)**

In [142]:
batsman = pd.read_csv('../04CampusX_DataSet/datasets-session-17/batsman_runs_ipl.csv')
batsman.head()

           batter  batsman_run
0  A Ashish Reddy          280
1        A Badoni          161
2      A Chandila            4
3        A Chopra           53
4     A Choudhary           25

In [143]:
batsman['batsman_run'].rank(ascending=False)
# Creates a series assigning ranks to the batsman runs in descending order
# each index of the series corresponds to the index of the batsman in the dataframe
# ranks are calculated based on the batsman_run column of the dataframe
# since ascending=False, rank 1 ---> highest run and so on
# two batsman with same runs will get the same rank and the next rank will be skipped
# for example, if two batsman have the highest run of 100, they will both get rank 1 and the next rank will be 3

0      166.5
1      226.0
2      535.0
3      329.0
4      402.5
       ...
600    594.0
601    343.0
602    547.5
603     27.0
604    256.0
Name: batsman_run, Length: 605, dtype: float64

In [144]:
# batsman['batting_rank'] => Creates a in DataFrame column named 'batting_rank' since no such column exists in the dataframe already.
# batsman['batsman_run'].rank(ascending=False) => Ranks the batsman runs in descending order and returns a series of ranks

batsman['batting_rank'] = batsman['batsman_run'].rank(ascending=False)
batsman.sort_values('batting_rank')

           batter  batsman_run  batting_rank
569       V Kohli         6634           1.0
462      S Dhawan         6244           2.0
130     DA Warner         5883           3.0
430     RG Sharma         5881           4.0
493      SK Raina         5536           5.0
..            ...          ...           ...
600    Yash Dayal            0         594.0
595    YA Abdulla            0         594.0
57         AS Roy            0         594.0
63   Abdur Razzak            0         594.0
65     Akash Deep            0         594.0

[605 rows x 3 columns]

# **4. sort_index() --->(series & dataframe)**

In [145]:
# Sample series 
marks = {
    'maths':67,
    'english':57,
    'science':89,
    'hindi':100
}

marks_series = pd.Series(marks)
marks_series

maths       67
english     57
science     89
hindi      100
dtype: int64

In [146]:
marks_series.sort_index(ascending=False)

science     89
maths       67
hindi      100
english     57
dtype: int64

In [147]:
movies.sort_index(ascending=False).head(2)

,title_x,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date
1628,Humsafar,tt2403201,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Humsafar,Humsafar,Humsafar,0,2011,35,Drama|Romance,9.0,2968,Sara and Ashar are childhood friends who share...,Ashar and Khirad are forced to get married due...,NaN,Fawad Khan|,NaN,TV Series (2011–2012)
1627,Daaka,tt10833860,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Daaka,Daaka,Daaka,0,2019,136,Action,7.4,38,Shinda tries robbing a bank so he can be wealt...,Shinda tries robbing a bank so he can be wealt...,NaN,Gippy Grewal|Zareen Khan|,NaN,1 November 2019 (USA)

#  **5. set_index() --->(dataframe)**

In [148]:
batsman.head()

           batter  batsman_run  batting_rank
0  A Ashish Reddy          280         166.5
1        A Badoni          161         226.0
2      A Chandila            4         535.0
3        A Chopra           53         329.0
4     A Choudhary           25         402.5

In [186]:
batsman.set_index(keys='batter').head(2)
# Without inplace it is a temporary change and the original dataframe will remain unchanged
# batsman.set_index('batter',inplace=True) # inplace parameter makes changes permanent

                batsman_run  batting_rank
batter
A Ashish Reddy          280         166.5
A Badoni                161         226.0

In [188]:
batsman.head() # original dataframe remains unchanged

           batter  batsman_run  batting_rank
0  A Ashish Reddy          280         166.5
1        A Badoni          161         226.0
2      A Chandila            4         535.0
3        A Chopra           53         329.0
4     A Choudhary           25         402.5

In [ ]:
# Lets make a permanent change to the dataframe by setting the index to 'batter' column
# batsman.set_index('batter',inplace=True)
batsman.head()

                batting_rank  batsman_run
batter
A Ashish Reddy         166.5          280
A Badoni               226.0          161
A Chandila             535.0            4
A Chopra               329.0           53
A Choudhary            402.5           25

# **6. reset_index() --->(series + dataframe)**
-> drop parameter

In [232]:
# To reset the index of the dataframe to default integer index and make the current index a column in the dataframe
# Execute
# batsman.reset_index(inplace=True)
batsman.head()

           batter  batting_rank  batsman_run
0  A Ashish Reddy         166.5          280
1        A Badoni         226.0          161
2      A Chandila         535.0            4
3        A Chopra         329.0           53
4     A Choudhary         402.5           25

In [ ]:
# Making batter index again for next question
# batsman.set_index('batter', inplace=True)
batsman.head()

                batting_rank  batsman_run
batter
A Ashish Reddy         166.5          280
A Badoni               226.0          161
A Chandila             535.0            4
A Chopra               329.0           53
A Choudhary            402.5           25

In [234]:
# how to replace existing index without loosing it 
        # If batter is the index, and we want to set batting_rank as the new index, we must first reset the index to make batter a column again and then set batting_rank as the new index. 
        # Note: If we directly set batting_rank as the new index without resetting the index, we will lose the batter column and it will not be available in the dataframe anymore.
batsman.set_index('batting_rank').head() # this will make batting_rank the new index but we will lose the batter column
batsman.reset_index().set_index('batting_rank').head()

                      batter  batsman_run
batting_rank
166.5         A Ashish Reddy          280
226.0               A Badoni          161
535.0             A Chandila            4
329.0               A Chopra           53
402.5            A Choudhary           25

In [235]:
batsman.head()

                batting_rank  batsman_run
batter
A Ashish Reddy         166.5          280
A Badoni               226.0          161
A Chandila             535.0            4
A Chopra               329.0           53
A Choudhary            402.5           25

In [ ]:
# batsman.reset_index(inplace=True)
batsman.head()

           batter  batting_rank  batsman_run
0  A Ashish Reddy         166.5          280
1        A Badoni         226.0          161
2      A Chandila         535.0            4
3        A Chopra         329.0           53
4     A Choudhary         402.5           25

In [237]:
# series to dataframe using reset_index
marks_series.reset_index()

     index    0
0    maths   67
1  english   57
2  science   89
3    hindi  100

# **7. rename() --->(dataframe)**
- columns - Change column names
- index - Change index values

In [263]:
movies = pd.read_csv('../04CampusX_DataSet/datasets-session-17/movies.csv')
movies.head(2)

,title_x,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date
0,Uri: The Surgical Strike,tt8291224,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Uri:_The_Surgica...,Uri: The Surgical Strike,Uri: The Surgical Strike,0,2019,138,Action|Drama|War,8.4,35112,Divided over five chapters the film chronicle...,Indian army special forces execute a covert op...,NaN,Vicky Kaushal|Paresh Rawal|Mohit Raina|Yami Ga...,4 wins,11 January 2019 (USA)
1,Battalion 609,tt9472208,NaN,https://en.wikipedia.org/wiki/Battalion_609,Battalion 609,Battalion 609,0,2019,131,War,4.1,73,The story revolves around a cricket match betw...,The story of Battalion 609 revolves around a c...,NaN,Vicky Ahuja|Shoaib Ibrahim|Shrikant Kamat|Elen...,NaN,11 January 2019 (India)

In [ ]:
# movies.set_index('title_x',inplace=True)
movies.head(2)

,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date
title_x,,,,,,,,,,,,,,,,,
Uri: The Surgical Strike,tt8291224,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Uri:_The_Surgica...,Uri: The Surgical Strike,Uri: The Surgical Strike,0,2019,138,Action|Drama|War,8.4,35112,Divided over five chapters the film chronicle...,Indian army special forces execute a covert op...,NaN,Vicky Kaushal|Paresh Rawal|Mohit Raina|Yami Ga...,4 wins,11 January 2019 (USA)
Battalion 609,tt9472208,NaN,https://en.wikipedia.org/wiki/Battalion_609,Battalion 609,Battalion 609,0,2019,131,War,4.1,73,The story revolves around a cricket match betw...,The story of Battalion 609 revolves around a c...,NaN,Vicky Ahuja|Shoaib Ibrahim|Shrikant Kamat|Elen...,NaN,11 January 2019 (India)

- renaming columns in movies dataset

In [266]:
movies.rename(columns={'imdb_id':'imdb','poster_path':'link'},inplace=True)
movies.head(3)

,imdb,link,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date
title_x,,,,,,,,,,,,,,,,,
Uri: The Surgical Strike,tt8291224,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Uri:_The_Surgica...,Uri: The Surgical Strike,Uri: The Surgical Strike,0,2019,138,Action|Drama|War,8.4,35112,Divided over five chapters the film chronicle...,Indian army special forces execute a covert op...,NaN,Vicky Kaushal|Paresh Rawal|Mohit Raina|Yami Ga...,4 wins,11 January 2019 (USA)
Battalion 609,tt9472208,NaN,https://en.wikipedia.org/wiki/Battalion_609,Battalion 609,Battalion 609,0,2019,131,War,4.1,73,The story revolves around a cricket match betw...,The story of Battalion 609 revolves around a c...,NaN,Vicky Ahuja|Shoaib Ibrahim|Shrikant Kamat|Elen...,NaN,11 January 2019 (India)
The Accidental Prime Minister (film),tt6986710,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/The_Accidental_P...,The Accidental Prime Minister,The Accidental Prime Minister,0,2019,112,Biography|Drama,6.1,5549,Based on the memoir by Indian policy analyst S...,Explores Manmohan Singh's tenure as the Prime ...,NaN,Anupam Kher|Akshaye Khanna|Aahana Kumra|Atul S...,NaN,11 January 2019 (USA)

- renaming index in movies dataset

In [268]:
movies.rename(index={'Uri: The Surgical Strike':'Uri','Battalion 609':'Battalion'}).head(3)

,imdb,link,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date
title_x,,,,,,,,,,,,,,,,,
Uri,tt8291224,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Uri:_The_Surgica...,Uri: The Surgical Strike,Uri: The Surgical Strike,0,2019,138,Action|Drama|War,8.4,35112,Divided over five chapters the film chronicle...,Indian army special forces execute a covert op...,NaN,Vicky Kaushal|Paresh Rawal|Mohit Raina|Yami Ga...,4 wins,11 January 2019 (USA)
Battalion,tt9472208,NaN,https://en.wikipedia.org/wiki/Battalion_609,Battalion 609,Battalion 609,0,2019,131,War,4.1,73,The story revolves around a cricket match betw...,The story of Battalion 609 revolves around a c...,NaN,Vicky Ahuja|Shoaib Ibrahim|Shrikant Kamat|Elen...,NaN,11 January 2019 (India)
The Accidental Prime Minister (film),tt6986710,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/The_Accidental_P...,The Accidental Prime Minister,The Accidental Prime Minister,0,2019,112,Biography|Drama,6.1,5549,Based on the memoir by Indian policy analyst S...,Explores Manmohan Singh's tenure as the Prime ...,NaN,Anupam Kher|Akshaye Khanna|Aahana Kumra|Atul S...,NaN,11 January 2019 (USA)

# **8. unique() vs nunique()**

unique() -> returns an **array of unique values** in a series # array(1,2,3,4,5,nan)
nunique() -> returns **count of unique values** in a series # 5

unique() -> Includes **nan as a unique value** in array it returns
len(unique()) -> will give you the count of unique values including nan

nunique() -> returns the count of unique values excluding nan

In [269]:
temp = pd.Series([1,1,2,2,3,3,4,4,5,5,np.nan,np.nan])
print(temp)

0     1.0
1     1.0
2     2.0
3     2.0
4     3.0
5     3.0
6     4.0
7     4.0
8     5.0
9     5.0
10    NaN
11    NaN
dtype: float64

In [278]:
len(temp.unique())

6

In [279]:
temp.nunique()

5

In [280]:
len(ipl['Season'].unique())

15

In [281]:
# nunique(series + dataframe) -> does not count nan -> dropna parameter
ipl['Season'].nunique()

15

# **9. isnull() | notnull() | hasnans()**
- isnull()  --->(series + dataframe) 
- notnull() --->(series + dataframe)
- hasnans() --->(series)

In [316]:
students = pd.DataFrame(
    {
        'name':['nitish','ankit','rupesh',np.nan,'mrityunjay',np.nan,'rishabh',np.nan,'aditya',np.nan],
        'college':['bit','iit','vit',np.nan,np.nan,'vlsi','ssit',np.nan,np.nan,'git'],
        'branch':['eee','it','cse',np.nan,'me','ce','civ','cse','bio',np.nan],
        'cgpa':[6.66,8.25,6.41,np.nan,5.6,9.0,7.4,10,7.4,np.nan],
        'package':[4,5,6,np.nan,6,7,8,9,np.nan,np.nan]

    }
)

students

         name college branch   cgpa  package
0      nitish     bit    eee   6.66      4.0
1       ankit     iit     it   8.25      5.0
2      rupesh     vit    cse   6.41      6.0
3         NaN     NaN    NaN    NaN      NaN
4  mrityunjay     NaN     me   5.60      6.0
5         NaN    vlsi     ce   9.00      7.0
6     rishabh    ssit    civ   7.40      8.0
7         NaN     NaN    cse  10.00      9.0
8      aditya     NaN    bio   7.40      NaN
9         NaN     git    NaN    NaN      NaN

- isnull | notnull | hasnan ---> On Series

In [294]:
students['name'].isnull()

0    False
1    False
2    False
3     True
4    False
5     True
6    False
7     True
8    False
9     True
Name: name, dtype: bool

In [300]:
students.loc[students['name'].isnull(), 'name']

3    NaN
5    NaN
7    NaN
9    NaN
Name: name, dtype: object

In [ ]:
# students.loc[students['name'].isnull(), 'name'] = 'unknown'
students

         name college branch   cgpa  package
0      nitish     bit    eee   6.66      4.0
1       ankit     iit     it   8.25      5.0
2      rupesh     vit    cse   6.41      6.0
3     unknown     NaN    NaN    NaN      NaN
4  mrityunjay     NaN     me   5.60      6.0
5     unknown    vlsi     ce   9.00      7.0
6     rishabh    ssit    civ   7.40      8.0
7     unknown     NaN    cse  10.00      9.0
8      aditya     NaN    bio   7.40      NaN
9     unknown     git    NaN    NaN      NaN

In [303]:
# notnull(series + dataframe)
# students['name'][students['name'].notnull()]
students.loc[students['name'].notnull(), 'name']

0        nitish
1         ankit
2        rupesh
4    mrityunjay
6       rishabh
8        aditya
Name: name, dtype: object

In [304]:
# hasnans(series)
students['name'].hasnans

True

In [307]:
students # remain unchanges as these are temporary operations without inplace parameter

         name college branch   cgpa  package
0      nitish     bit    eee   6.66      4.0
1       ankit     iit     it   8.25      5.0
2      rupesh     vit    cse   6.41      6.0
3         NaN     NaN    NaN    NaN      NaN
4  mrityunjay     NaN     me   5.60      6.0
5         NaN    vlsi     ce   9.00      7.0
6     rishabh    ssit    civ   7.40      8.0
7         NaN     NaN    cse  10.00      9.0
8      aditya     NaN    bio   7.40      NaN
9         NaN     git    NaN    NaN      NaN

- isnull | notnull | hasnan ---> DataFrame

In [306]:
students.isnull()

    name  college  branch   cgpa  package
0  False    False   False  False    False
1  False    False   False  False    False
2  False    False   False  False    False
3   True     True    True   True     True
4  False     True   False  False    False
5   True    False   False  False    False
6  False    False   False  False    False
7   True     True   False  False    False
8  False     True   False  False     True
9   True    False    True   True     True

In [170]:
students.notnull()

    name  college  branch   cgpa  package
3  False    False   False  False    False
5  False     True    True   True     True
7  False    False    True   True     True
9  False     True   False  False    False
8   True    False    True   True    False
1   True     True    True   True     True
4   True    False    True   True     True
0   True     True    True   True     True
6   True     True    True   True     True
2   True     True    True   True     True

# **10. dropna() --->(series + dataframe)**
parameters:
- how -> any | all
- inplace -> True | False
- subset -> list of columns on which dropna will be applied, if not given then it is applied on all the columns

### CASE 1: dropna() on series

In [ ]:
students['name'].dropna()

0        nitish
1         ankit
2        rupesh
4    mrityunjay
6       rishabh
8        aditya
Name: name, dtype: object

In [310]:
students

         name college branch   cgpa  package
0      nitish     bit    eee   6.66      4.0
1       ankit     iit     it   8.25      5.0
2      rupesh     vit    cse   6.41      6.0
3         NaN     NaN    NaN    NaN      NaN
4  mrityunjay     NaN     me   5.60      6.0
5         NaN    vlsi     ce   9.00      7.0
6     rishabh    ssit    civ   7.40      8.0
7         NaN     NaN    cse  10.00      9.0
8      aditya     NaN    bio   7.40      NaN
9         NaN     git    NaN    NaN      NaN

### CASE 2: dropna() on entire dataframe

- parameter: how -> any | all

In [ ]:
students.dropna(how='any') # 'any' is the default value of how parameter and it drops the rows where any of the values is null

      name college branch  cgpa  package
1    ankit     iit     it  8.25      5.0
0   nitish     bit    eee  6.66      4.0
6  rishabh    ssit    civ  7.40      8.0
2   rupesh     vit    cse  6.41      6.0

In [312]:
students.dropna(how='all') # 'all' drops the rows where all the values are null, over here row index 3 is dropped

         name college branch   cgpa  package
0      nitish     bit    eee   6.66      4.0
1       ankit     iit     it   8.25      5.0
2      rupesh     vit    cse   6.41      6.0
4  mrityunjay     NaN     me   5.60      6.0
5         NaN    vlsi     ce   9.00      7.0
6     rishabh    ssit    civ   7.40      8.0
7         NaN     NaN    cse  10.00      9.0
8      aditya     NaN    bio   7.40      NaN
9         NaN     git    NaN    NaN      NaN

### CASE 3: dropna() on subset of columns in dataframe
Parameter: subset -> list of columns on which dropna will be applied, if not given then it is applied on all the columns

In [315]:
students.dropna(subset=['name']) # Drops all the rows where 'name' is null

         name college branch  cgpa  package
0      nitish     bit    eee  6.66      4.0
1       ankit     iit     it  8.25      5.0
2      rupesh     vit    cse  6.41      6.0
4  mrityunjay     NaN     me  5.60      6.0
6     rishabh    ssit    civ  7.40      8.0
8      aditya     NaN    bio  7.40      NaN

In [ ]:
students.dropna(subset=['name','college']) # Drops all the rows where 'name' or 'college' is null, resulting in output where neither 'name' nor 'college' is null in the output dataframe

      name college branch  cgpa  package
1    ankit     iit     it  8.25      5.0
0   nitish     bit    eee  6.66      4.0
6  rishabh    ssit    civ  7.40      8.0
2   rupesh     vit    cse  6.41      6.0

In [ ]:
# inplace parameter to make permanent changes to the dataframe
# students.dropna(inplace=True)

# **11. fillna() --->(series + dataframe)**
- value -> scalar value or dictionary of column names and values to fill null values with
- mathematical operations -> 'mean', 'median', 'mode'
- method -> 'ffill' | 'bfill' (forward fill or backward fill)

In [322]:
students = pd.DataFrame(
    {
        'name':['nitish','ankit','rupesh',np.nan,'mrityunjay',np.nan,'rishabh',np.nan,'aditya',np.nan],
        'college':['bit','iit','vit',np.nan,np.nan,'vlsi','ssit',np.nan,np.nan,'git'],
        'branch':['eee','it','cse',np.nan,'me','ce','civ','cse','bio',np.nan],
        'cgpa':[6.66,8.25,6.41,np.nan,5.6,9.0,7.4,10,7.4,np.nan],
        'package':[4,5,6,np.nan,6,7,8,9,np.nan,np.nan]

    }
)

students

         name college branch   cgpa  package
0      nitish     bit    eee   6.66      4.0
1       ankit     iit     it   8.25      5.0
2      rupesh     vit    cse   6.41      6.0
3         NaN     NaN    NaN    NaN      NaN
4  mrityunjay     NaN     me   5.60      6.0
5         NaN    vlsi     ce   9.00      7.0
6     rishabh    ssit    civ   7.40      8.0
7         NaN     NaN    cse  10.00      9.0
8      aditya     NaN    bio   7.40      NaN
9         NaN     git    NaN    NaN      NaN

In [ ]:
# fillna Scalar value
students['name'].fillna('unknown') # Temporary Operation

0        nitish
1         ankit
2        rupesh
3       unknown
4    mrityunjay
5       unknown
6       rishabh
7       unknown
8        aditya
9       unknown
Name: name, dtype: object

In [ ]:
# same can be achived by
# students.loc[students['name'].isnull(), 'name'] = 'HakuNaMatata' # DownSide = Its Permanent operation
students

           name college branch   cgpa  package
0        nitish     bit    eee   6.66      4.0
1         ankit     iit     it   8.25      5.0
2        rupesh     vit    cse   6.41      6.0
3  HakuNaMatata     NaN    NaN    NaN      NaN
4    mrityunjay     NaN     me   5.60      6.0
5  HakuNaMatata    vlsi     ce   9.00      7.0
6       rishabh    ssit    civ   7.40      8.0
7  HakuNaMatata     NaN    cse  10.00      9.0
8        aditya     NaN    bio   7.40      NaN
9  HakuNaMatata     git    NaN    NaN      NaN

In [324]:
students

         name college branch   cgpa  package
0      nitish     bit    eee   6.66      4.0
1       ankit     iit     it   8.25      5.0
2      rupesh     vit    cse   6.41      6.0
3         NaN     NaN    NaN    NaN      NaN
4  mrityunjay     NaN     me   5.60      6.0
5         NaN    vlsi     ce   9.00      7.0
6     rishabh    ssit    civ   7.40      8.0
7         NaN     NaN    cse  10.00      9.0
8      aditya     NaN    bio   7.40      NaN
9         NaN     git    NaN    NaN      NaN

In [ ]:
# fillna by mathematical operation
students['package'].fillna(students['package'].mean())

0    4.000000
1    5.000000
2    6.000000
3    6.428571
4    6.000000
5    7.000000
6    8.000000
7    9.000000
8    6.428571
9    6.428571
Name: package, dtype: float64

In [ ]:
# fillna by method
students['name'].ffill() 
# forward fill method fills the null values with the last non-null value in the column, if there is no non-null value before the null value, it will remain null

0        nitish
1         ankit
2        rupesh
3        rupesh
4    mrityunjay
5    mrityunjay
6       rishabh
7       rishabh
8        aditya
9        aditya
Name: name, dtype: object

In [328]:
students['name'].bfill()
# backward fill method fills the null values with the next non-null value in the column, if there is no non-null value after the null value, it will remain null

0        nitish
1         ankit
2        rupesh
3    mrityunjay
4    mrityunjay
5       rishabh
6       rishabh
7        aditya
8        aditya
9           NaN
Name: name, dtype: object

# **12. drop_duplicates(series + dataframe)**
-> works like and 
-> duplicated()

### CASE 1: drop_duplicates() on series

In [183]:
temp = pd.Series([1,1,1,2,3,3,4,4])
temp.drop_duplicates()

0    1
3    2
4    3
6    4
dtype: int64

### CASE 2: dropna() on dataframe

Parameter: keep -> first | last | False

In [331]:
marks = pd.DataFrame([
    [100,80,10],
    [90,70,7],
    [120,100,14],
    [80,70,14],
    [80,70,14]
],columns=['iq','marks','package'])

marks

    iq  marks  package
0  100     80       10
1   90     70        7
2  120    100       14
3   80     70       14
4   80     70       14

In [ ]:
# without any parameter, it will drop all the duplicate rows and keep the first occurrence of each duplicate row
marks.drop_duplicates() # default keep is first

    iq  marks  package
0  100     80       10
1   90     70        7
2  120    100       14
4   80     70       14

In [334]:
# it keeps last occurrence of each duplicate row and drops the rest
marks.drop_duplicates(keep='last')

    iq  marks  package
0  100     80       10
1   90     70        7
2  120    100       14
4   80     70       14

In [ ]:
# find the last match played by virat kohli in Delhi via drop duplicate
ipl['all_players'] = ipl['Team1Players'] + ipl['Team2Players'] # created a new col
ipl.head(2)

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,...,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2,all_players
0,1312200,Ahmedabad,2022-05-29,2022,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,...,Gujarat Titans,Wickets,7.0,NaN,HH Pandya,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",CB Gaffaney,Nitin Menon,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ..."
1,1312199,Ahmedabad,2022-05-27,2022,Qualifier 2,Royal Challengers Bangalore,Rajasthan Royals,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,field,...,Rajasthan Royals,Wickets,7.0,NaN,JC Buttler,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...",CB Gaffaney,Nitin Menon,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ..."

In [ ]:
def did_kohli_play(players_list): # checks if 'V Kohli' is in the list of players
  return 'V Kohli' in players_list

In [ ]:
# final answer 
ipl['did_kohli_play'] = ipl['all_players'].apply(did_kohli_play)
ipl[(ipl['City'] == 'Delhi') & (ipl['did_kohli_play'] == True)].drop_duplicates(subset=['City','did_kohli_play'],keep='first')

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,...,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2,all_players,did_kohli_play
208,1178421,Delhi,2019-04-28,2019,46,Delhi Capitals,Royal Challengers Bangalore,Arun Jaitley Stadium,Delhi Capitals,bat,...,Runs,16.0,NaN,S Dhawan,"['PP Shaw', 'S Dhawan', 'SS Iyer', 'RR Pant', ...","['PA Patel', 'V Kohli', 'AB de Villiers', 'S D...",BNJ Oxenford,KN Ananthapadmanabhan,"['PP Shaw', 'S Dhawan', 'SS Iyer', 'RR Pant', ...",True

In [ ]:
students.drop_duplicates()

# **13. drop(series + dataframe)**

In [336]:
temp = pd.Series([10,2,3,16,45,78,10])
temp

0    10
1     2
2     3
3    16
4    45
5    78
6    10
dtype: int64

In [337]:
temp.drop(index=[0,6])

1     2
2     3
3    16
4    45
5    78
dtype: int64

In [338]:
students

         name college branch   cgpa  package
0      nitish     bit    eee   6.66      4.0
1       ankit     iit     it   8.25      5.0
2      rupesh     vit    cse   6.41      6.0
3         NaN     NaN    NaN    NaN      NaN
4  mrityunjay     NaN     me   5.60      6.0
5         NaN    vlsi     ce   9.00      7.0
6     rishabh    ssit    civ   7.40      8.0
7         NaN     NaN    cse  10.00      9.0
8      aditya     NaN    bio   7.40      NaN
9         NaN     git    NaN    NaN      NaN

In [ ]:
students.drop(columns=['branch','cgpa'])
# students.drop(columns=['branch','cgpa'],inplace=True) # will make changes permanent

         name college  package
0      nitish     bit      4.0
1       ankit     iit      5.0
2      rupesh     vit      6.0
3         NaN     NaN      NaN
4  mrityunjay     NaN      6.0
5         NaN    vlsi      7.0
6     rishabh    ssit      8.0
7         NaN     NaN      9.0
8      aditya     NaN      NaN
9         NaN     git      NaN

In [341]:
students.set_index('name').drop(index=['nitish','aditya'])

           college branch   cgpa  package
name
ankit          iit     it   8.25      5.0
rupesh         vit    cse   6.41      6.0
NaN            NaN    NaN    NaN      NaN
mrityunjay     NaN     me   5.60      6.0
NaN           vlsi     ce   9.00      7.0
rishabh       ssit    civ   7.40      8.0
NaN            NaN    cse  10.00      9.0
NaN            git    NaN    NaN      NaN

# **14. apply() --->(series + dataframe)**

In [ ]:
temp = pd.Series([10,20,30,40,50])

temp

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [ ]:
def sigmoid(value):
  return 1/1+np.exp(-value)

In [ ]:
temp.apply(sigmoid)

0    1.000045
1    1.000000
2    1.000000
3    1.000000
4    1.000000
dtype: float64

In [ ]:
points_df = pd.DataFrame(
    {
        '1st point':[(3,4),(-6,5),(0,0),(-10,1),(4,5)],
        '2nd point':[(-3,4),(0,0),(2,2),(10,10),(1,1)]
    }
)

points_df

  1st point 2nd point
0    (3, 4)   (-3, 4)
1   (-6, 5)    (0, 0)
2    (0, 0)    (2, 2)
3  (-10, 1)  (10, 10)
4    (4, 5)    (1, 1)

In [ ]:
def euclidean(row):
  pt_A = row['1st point']
  pt_B = row['2nd point']

  return ((pt_A[0] - pt_B[0])**2 + (pt_A[1] - pt_B[1])**2)**0.5

In [ ]:
points_df['distance'] = points_df.apply(euclidean,axis=1)
points_df

  1st point 2nd point   distance
0    (3, 4)   (-3, 4)   6.000000
1   (-6, 5)    (0, 0)   7.810250
2    (0, 0)    (2, 2)   2.828427
3  (-10, 1)  (10, 10)  21.931712
4    (4, 5)    (1, 1)   5.000000

In [ ]:
# isin(series)

In [ ]:
# corr

In [ ]:
# nlargest and nsmallest(series and dataframe)

In [ ]:
# insert(dataframe)

In [ ]:
# copy(series + dataframe)