In [1]:
import numpy as np
import pandas as pd

In [3]:
movies = pd.read_csv('../04CampusX_DataSet/dataset-session-19/imdb-top-1000.csv')
movies.head()

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
0,The Shawshank Redemption ...,1994,142,Drama,9.3,Frank Darabont,Tim Robbins,2343110,28341469.0,80.0
1,The Godfather ...,1972,175,Crime,9.2,Francis Ford Coppola,Marlon Brando,1620367,134966411.0,100.0
2,The Dark Knight ...,2008,152,Action,9.0,Christopher Nolan,Christian Bale,2303232,534858444.0,84.0
3,The Godfather: Part II ...,1974,202,Crime,9.0,Francis Ford Coppola,Al Pacino,1129952,57300000.0,90.0
4,12 Angry Men ...,1957,96,Crime,9.0,Sidney Lumet,Henry Fonda,689845,4360000.0,96.0

In [7]:
# striping white space from col name
movies.columns = movies.columns.str.strip()

# **Creating a Group**

In [8]:
genres = movies.groupby('Genre')
# movies.columns

In [9]:
genres

# **Applying operations on groups**

In [10]:
# Applying builtin aggregation fuctions on groupby objects
genres.std(numeric_only=True).head()

             Runtime  IMDB_Rating    No_of_Votes         Gross
Genre
Action     28.500706     0.304258  432946.814748  2.256724e+08
Adventure  33.317320     0.229781  301188.347642  1.697543e+08
Animation  14.530471     0.253221  262173.231571  2.091840e+08
Biography  25.514466     0.267140  271284.191372  1.363251e+08
Comedy     22.946213     0.228771  188653.570564  1.946513e+08

# **Practice Problem on Group**

In [11]:
mode = movies["Runtime"].mode()
# movies["Runtime"].mode()
# s.value_counts().loc[mode]
movies["Runtime"].value_counts().loc[movies["Runtime"].mode()]

Runtime
100    23
130    23
Name: count, dtype: int64

In [12]:
# # find the top 3 genres by total earning
# movies.groupby('Genre').sum(numeric_only=True)['Gross'].sort_values(ascending=False).head(3)
movies.groupby('Genre')['Gross'].sum(numeric_only=True).sort_values(ascending=False).head(3) #Better way

Genre
Drama        3.540997e+10
Action       3.263226e+10
Comedy       1.566387e+10
Name: Gross, dtype: float64

In [13]:
# find the genre with highest avg IMDB rating
movies.groupby('Genre')['IMDB_Rating'].mean().sort_values(ascending=False).head(1)

Genre
Western      8.35
Name: IMDB_Rating, dtype: float64

In [14]:
# find director with most popularity
movies.groupby('Director')['No_of_Votes'].sum().sort_values(ascending=False).head(1)

Director
Christopher Nolan                   11578345
Name: No_of_Votes, dtype: int64

In [15]:
# find the highest rated movie of each genre
max = movies.groupby('Genre')['IMDB_Rating'].transform("max")
movies.loc[movies['IMDB_Rating'] == max]

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
0,The Shawshank Redemption ...,1994,142,Drama,9.3,Frank Darabont,Tim Robbins,2343110,28341469.0,80.0
1,The Godfather ...,1972,175,Crime,9.2,Francis Ford Coppola,Marlon Brando,1620367,134966411.0,100.0
2,The Dark Knight ...,2008,152,Action,9.0,Christopher Nolan,Christian Bale,2303232,534858444.0,84.0
7,Schindler's List ...,1993,195,Biography,8.9,Steven Spielberg,Liam Neeson,1213505,96898818.0,94.0
12,"Il buono, il brutto, il cattivo ...",1966,161,Western,8.8,Sergio Leone,Clint Eastwood,688390,6100000.0,90.0
19,Gisaengchung ...,2019,132,Comedy,8.6,Bong Joon Ho,Kang-ho Song,552778,53367844.0,96.0
21,Interstellar ...,2014,169,Adventure,8.6,Christopher Nolan,Matthew McConaughey,1512360,188020017.0,74.0
23,Sen to Chihiro no kamikakushi ...,2001,125,Animation,8.6,Hayao Miyazaki,Daveigh Chase,651376,10055859.0,96.0
26,La vita è bella ...,1997,116,Comedy,8.6,Roberto Benigni,Roberto Benigni,623629,57598247.0,59.0
49,Psycho ...,1960,109,Horror,8.5,Alfred Hitchcock,Anthony Perkins,604211,32000000.0,97.0
69,Memento ...,2000,113,Mystery,8.4,Christopher Nolan,Guy Pearce,1125712,25544867.0,80.0
81,Rear Window ...,1954,112,Mystery,8.4,Alfred Hitchcock,James Stewart,444074,36764313.0,100.0
309,The Third Man ...,1949,104,Film-Noir,8.1,Carol Reed,Orson Welles,158731,449191.0,97.0
321,Das Cabinet des Dr. Caligari ...,1920,76,Fantasy,8.1,Robert Wiene,Werner Krauss,57428,337574718.0,
688,E.T. the Extra-Terrestrial ...,1982,115,Family,7.8,Steven Spielberg,Henry Thomas,372490,435110554.0,91.0
698,Willy Wonka & the Chocolate Factory ...,1971,100,Family,7.8,Mel Stuart,Gene Wilder,178731,4000000.0,67.0
700,Wait Until Dark ...,1967,108,Thriller,7.8,Terence Young,Audrey Hepburn,27733,17550741.0,81.0

In [16]:
# find number of movies done by each actor
movies.groupby('Star1')['Series_Title'].count().sort_values(ascending=False) # ignore the row if selected col is nan
movies.groupby('Star1').size().sort_values(ascending=False) # counts rows in group

Star1
Tom Hanks                    12
Robert De Niro               11
Al Pacino                    10
Clint Eastwood               10
Humphrey Bogart               9
                             ..
Günes Sensoy                  1
Haluk Bilginer                1
Harriet Andersson             1
Harry Dean Stanton            1
Griffin Dunne                 1
Length: 660, dtype: int64

# **GroupBy Attributes, Methods and Functions**

In [17]:
# GroupBy Attributes and Methods
# find total number of groups -> len
# find items in each group -> size
# first()/last() -> nth item
# get_group -> vs filtering
# groups
# describe
# sample
# nunique

#### 1. Find total number of groups -> len

In [18]:
# find total number of groups -> len
len(movies.groupby('Genre'))

14

In [19]:
# find no. of unique Genres without groupby --> nunique
movies['Genre'].nunique()

14

#### 2. Find items in each group -> size

In [20]:
# find items in each group -> size
movies.groupby('Genre').size()

Genre
Action       172
Adventure     72
Animation     82
Biography     88
Comedy       155
Crime        107
Drama        289
Family         2
Fantasy        2
Film-Noir      3
Horror        11
Mystery       12
Thriller       1
Western        4
dtype: int64

#### 3.  first() | last() | nth() item

In [21]:
genres = movies.groupby('Genre')
# genres.first()
# genres.last()
genres.nth(6)

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
16,Star Wars: Episode V - The Empire Strikes Back...,1980,124,Action,8.7,Irvin Kershner,Mark Hamill,1159315,290475067.0,82.0
27,Se7en ...,1995,127,Crime,8.6,David Fincher,Morgan Freeman,1445096,100125643.0,65.0
32,It's a Wonderful Life ...,1946,130,Drama,8.6,Frank Capra,James Stewart,405801,82385199.0,89.0
66,WALL·E ...,2008,98,Animation,8.4,Andrew Stanton,Ben Burtt,999790,223808164.0,95.0
83,The Great Dictator ...,1940,125,Comedy,8.4,Charles Chaplin,Charles Chaplin,203150,288475.0,
102,Braveheart ...,1995,178,Biography,8.3,Mel Gibson,Mel Gibson,959181,75600000.0,68.0
118,North by Northwest ...,1959,136,Adventure,8.3,Alfred Hitchcock,Cary Grant,299198,13275000.0,98.0
420,Sleuth ...,1972,138,Mystery,8.0,Joseph L. Mankiewicz,Laurence Olivier,44748,4081254.0,
724,Get Out ...,2017,104,Horror,7.7,Jordan Peele,Daniel Kaluuya,492851,176040665.0,85.0

In [22]:
movies['Genre'].value_counts()

Genre
Drama        289
Action       172
Comedy       155
Crime        107
Biography     88
Animation     82
Adventure     72
Mystery       12
Horror        11
Western        4
Film-Noir      3
Fantasy        2
Family         2
Thriller       1
Name: count, dtype: int64

In [23]:
# removing white space in data
movies['Genre'] = movies['Genre'].str.strip()
genres = movies.groupby(by='Genre')

In [24]:
for genre in movies['Genre'].unique():
    print(repr(genre))

'Drama'
'Crime'
'Action'
'Biography'
'Western'
'Comedy'
'Adventure'
'Animation'
'Horror'
'Mystery'
'Film-Noir'
'Fantasy'
'Family'
'Thriller'

#### 4. get_group -> vs filtering

In [25]:
genres.get_group('Fantasy')
# movies[movies['Genre'] == 'Fantasy']

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
321,Das Cabinet des Dr. Caligari ...,1920,76,Fantasy,8.1,Robert Wiene,Werner Krauss,57428,337574718.0,
568,Nosferatu ...,1922,94,Fantasy,7.9,F.W. Murnau,Max Schreck,88794,445151978.0,

#### 5. groups

In [26]:
genres.groups

{'Action': [2, 5, 8, 10, 13, 14, 16, 29, 30, 31, 39, 42, 44, 55, 57, 59, 60, 63, 68, 72, 106, 109, 129, 130, 134, 140, 142, 144, 152, 155, 160, 161, 166, 168, 171, 172, 177, 181, 194, 201, 202, 216, 217, 223, 224, 236, 241, 262, 275, 294, 308, 320, 325, 326, 331, 337, 339, 340, 343, 345, 348, 351, 353, 356, 357, 362, 368, 369, 375, 376, 390, 410, 431, 436, 473, 477, 479, 482, 488, 493, 496, 502, 507, 511, 532, 535, 540, 543, 564, 569, 570, 573, 577, 582, 583, 602, 605, 608, 615, 623, ...], 'Adventure': [21, 47, 93, 110, 114, 116, 118, 137, 178, 179, 191, 193, 209, 226, 231, 247, 267, 273, 281, 300, 301, 304, 306, 323, 329, 361, 366, 377, 402, 406, 415, 426, 458, 470, 497, 498, 506, 513, 514, 537, 549, 552, 553, 566, 576, 604, 609, 618, 638, 647, 675, 681, 686, 692, 711, 713, 739, 755, 781, 797, 798, 851, 873, 884, 912, 919, 947, 957, 964, 966, 984, 991], 'Animation': [23, 43, 46, 56, 58, 61, 66, 70, 101, 135, 146, 151, 158, 170, 197, 205, 211, 213, 219, 229, 230, 242, 245, 246, 270, 330, 332, 358, 367, 378, 386, 389, 394, 395, 399, 401, 405, 409, 469, 499, 510, 516, 518, 522, 578, 586, 592, 595, 596, 599, 633, 640, 643, 651, 665, 672, 694, 728, 740, 741, 744, 756, 758, 761, 771, 783, 796, 799, 822, 828, 843, 875, 891, 892, 902, 906, 920, 956, 971, 976, 986, 992], 'Biography': [7, 15, 18, 35, 38, 54, 102, 107, 131, 139, 147, 157, 159, 173, 176, 212, 215, 218, 228, 235, 243, 263, 276, 282, 290, 298, 317, 328, 338, 342, 346, 359, 360, 365, 372, 373, 385, 411, 416, 418, 424, 429, 484, 525, 536, 542, 545, 575, 579, 587, 600, 606, 614, 622, 632, 635, 644, 649, 650, 657, 671, 673, 684, 729, 748, 753, 757, 759, 766, 770, 779, 809, 810, 815, 820, 831, 849, 858, 877, 882, 897, 910, 915, 923, 940, 949, 952, 987], 'Comedy': [19, 26, 51, 52, 64, 78, 83, 95, 96, 112, 117, 120, 127, 128, 132, 153, 169, 183, 192, 204, 207, 208, 214, 221, 233, 238, 240, 250, 251, 252, 256, 261, 266, 277, 284, 311, 313, 316, 318, 322, 327, 374, 379, 381, 392, 396, 403, 413, 414, 417, 427, 435, 445, 446, 449, 455, 459, 460, 463, 464, 466, 471, 472, 475, 481, 490, 494, 500, 503, 509, 526, 528, 530, 531, 533, 538, 539, 541, 547, 557, 558, 562, 563, 565, 574, 591, 593, 594, 598, 613, 626, 630, 660, 662, 667, 679, 680, 683, 687, 701, ...], 'Crime': [1, 3, 4, 6, 22, 25, 27, 28, 33, 37, 41, 71, 77, 79, 86, 87, 103, 108, 111, 113, 123, 125, 133, 136, 162, 163, 164, 165, 180, 186, 187, 189, 198, 222, 232, 239, 255, 257, 287, 288, 299, 305, 335, 363, 364, 380, 384, 397, 437, 438, 441, 442, 444, 450, 451, 465, 474, 480, 485, 487, 505, 512, 519, 520, 523, 527, 546, 556, 560, 584, 597, 603, 607, 611, 621, 639, 653, 664, 669, 676, 695, 708, 723, 762, 763, 767, 775, 791, 795, 802, 811, 823, 827, 833, 885, 895, 921, 922, 926, 938, ...], 'Drama': [0, 9, 11, 17, 20, 24, 32, 34, 36, 40, 45, 50, 53, 62, 65, 67, 73, 74, 76, 80, 82, 84, 85, 88, 89, 90, 91, 92, 94, 97, 98, 99, 100, 104, 105, 121, 122, 124, 126, 138, 141, 143, 148, 149, 150, 154, 156, 167, 174, 175, 182, 184, 185, 188, 190, 195, 196, 199, 200, 203, 206, 210, 225, 227, 234, 237, 244, 248, 249, 253, 254, 258, 259, 260, 264, 265, 268, 269, 272, 274, 278, 279, 280, 283, 285, 286, 289, 291, 292, 293, 295, 296, 297, 302, 303, 307, 310, 312, 314, 315, ...], 'Family': [688, 698], 'Fantasy': [321, 568], 'Film-Noir': [309, 456, 712], 'Horror': [49, 75, 271, 419, 544, 707, 724, 844, 876, 932, 948], 'Mystery': [69, 81, 119, 145, 220, 393, 420, 714, 829, 899, 959, 961], 'Thriller': [700], 'Western': [12, 48, 115, 691]}

#### 6. describe

In [27]:
genres.describe()

          Runtime                                                              \
            count        mean        std    min     25%    50%     75%    max
Genre
Action      172.0  129.046512  28.500706   45.0  110.75  127.5  143.25  321.0
Adventure    72.0  134.111111  33.317320   88.0  109.00  127.0  149.00  228.0
Animation    82.0   99.585366  14.530471   71.0   90.00   99.5  106.75  137.0
Biography    88.0  136.022727  25.514466   93.0  120.00  129.0  146.25  209.0
Comedy      155.0  112.129032  22.946213   68.0   96.00  106.0  124.50  188.0
Crime       107.0  126.392523  27.689231   80.0  106.50  122.0  141.50  229.0
Drama       289.0  124.737024  27.740490   64.0  105.00  121.0  137.00  242.0
Family        2.0  107.500000  10.606602  100.0  103.75  107.5  111.25  115.0
Fantasy       2.0   85.000000  12.727922   76.0   80.50   85.0   89.50   94.0
Film-Noir     3.0  104.000000   4.000000  100.0  102.00  104.0  106.00  108.0
Horror       11.0  102.090909  13.604812   71.0   98.00  103.0  109.00  122.0
Mystery      12.0  119.083333  14.475423   96.0  110.75  117.5  130.25  138.0
Thriller      1.0  108.000000        NaN  108.0  108.00  108.0  108.00  108.0
Western       4.0  148.250000  17.153717  132.0  134.25  148.0  162.00  165.0

          IMDB_Rating            ... No_of_Votes             Gross  \
                count      mean  ...         75%        max  count
Genre                            ...
Action          172.0  7.949419  ...   611174.00  2303232.0  172.0
Adventure        72.0  7.937500  ...   499798.00  1512360.0   72.0
Animation        82.0  7.930488  ...   378923.75   999790.0   82.0
Biography        88.0  7.938636  ...   369137.50  1213505.0   88.0
Comedy          155.0  7.901290  ...   242759.00   939631.0  155.0
Crime           107.0  8.016822  ...   444545.00  1826188.0  107.0
Drama           289.0  7.957439  ...   246963.00  2343110.0  289.0
Family            2.0  7.800000  ...   324050.25   372490.0    2.0
Fantasy           2.0  8.000000  ...    80952.50    88794.0    2.0
Film-Noir         3.0  7.966667  ...   153829.50   158731.0    3.0
Horror           11.0  7.909091  ...   435935.50   787806.0   11.0
Mystery          12.0  7.975000  ...   477666.25  1129894.0   12.0
Thriller          1.0  7.800000  ...    27733.00    27733.0    1.0
Western           4.0  8.350000  ...   399230.50   688390.0    4.0

                                                                               \
                   mean           std          min           25%          50%
Genre
Action     1.897224e+08  2.256724e+08       3296.0  2.402154e+07  103858027.5
Adventure  1.319017e+08  1.697543e+08      61001.0  1.323691e+07   57160627.0
Animation  1.784326e+08  2.091840e+08     128985.0  5.065330e+06  145219819.0
Biography  9.404952e+07  1.363251e+08      21877.0  2.464053e+07   51710054.0
Comedy     1.010572e+08  1.946513e+08       1305.0  2.918236e+06   19516000.0
Crime      7.899656e+07  1.571191e+08       6013.0  2.136032e+06   16290476.0
Drama      1.225259e+08  2.201164e+08       3600.0  2.603061e+06   18500194.0
Family     2.195553e+08  3.048412e+08    4000000.0  1.117776e+08  219555277.0
Fantasy    3.913633e+08  7.606861e+07  337574718.0  3.644690e+08  391363348.0
Film-Noir  4.197018e+07  7.048472e+07     449191.0  1.278626e+06    2108060.0
Horror     9.405902e+07  9.965017e+07      89029.0  2.289142e+07   56000369.0
Mystery    1.047014e+08  1.567524e+08    1035953.0  4.010115e+06   31154590.0
Thriller   1.755074e+07           NaN   17550741.0  1.755074e+07   17550741.0
Western    1.455538e+07  1.230626e+07    5321508.0  5.905377e+06   10550000.0


                    75%          max
Genre
Action     2.674437e+08  936662225.0
Adventure  1.998070e+08  874211619.0
Animation  2.520612e+08  873839108.0
Biography  9.829924e+07  753585104.0
Comedy     8.107809e+07  886752933.0
Crime      7.102163e+07  790482117.0
Drama      1.164461e+08  924558264.0
Family     3.273329e+08  435110554.0
Fantasy    4.182577e+08  445151978.0
Film-Noir  6.273068e+07  123353292.0
Horror     1.362817e+08  298791505.0
Mystery    1.310949e+08  474203697.0
Thriller   1.755074e+07   17550741.0
Western    1.920000e+07   31800000.0

[14 rows x 32 columns]

#### 7. sample

In [28]:
genres.sample(2,replace=True)

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
602,Ang-ma-reul bo-at-da ...,2010,144,Action,7.8,Jee-woon Kim,Lee Byung-Hun,111252,128392.0,67.0
850,Enter the Dragon ...,1973,102,Action,7.7,Robert Clouse,Bruce Lee,96561,25000000.0,83.0
713,Stagecoach ...,1939,96,Adventure,7.8,John Ford,John Wayne,43621,404971331.0,93.0
323,Togo ...,2019,113,Adventure,8.0,Ericson Core,Willem Dafoe,37556,874211619.0,69.0
56,Kimi no na wa. ...,2016,106,Animation,8.4,Makoto Shinkai,Ryûnosuke Kamiki,194838,5017246.0,79.0
386,Pâfekuto burû ...,1997,81,Animation,8.0,Satoshi Kon,Junko Iwao,58192,776665.0,
338,The Imitation Game ...,2014,114,Biography,8.0,Morten Tyldum,Benedict Cumberbatch,685201,91125683.0,73.0
215,12 Years a Slave ...,2013,134,Biography,8.1,Steve McQueen,Chiwetel Ejiofor,640533,56671993.0,96.0
794,Hedwig and the Angry Inch ...,2001,95,Comedy,7.7,John Cameron Mitchell,John Cameron Mitchell,31957,3029081.0,85.0
95,Amélie ...,2001,122,Comedy,8.3,Jean-Pierre Jeunet,Audrey Tautou,703810,33225499.0,69.0
198,Contratiempo ...,2016,106,Crime,8.1,Oriol Paulo,Mario Casas,141516,29756639.0,
77,Tengoku to jigoku ...,1963,143,Crime,8.4,Akira Kurosawa,Toshirô Mifune,34357,620361655.0,
244,Amores perros ...,2000,154,Drama,8.1,Alejandro G. Iñárritu,Emilio Echevarría,223741,5383834.0,83.0
92,Babam ve Oglum ...,2005,112,Drama,8.3,Çagan Irmak,Çetin Tekindor,78925,461855363.0,
688,E.T. the Extra-Terrestrial ...,1982,115,Family,7.8,Steven Spielberg,Henry Thomas,372490,435110554.0,91.0
688,E.T. the Extra-Terrestrial ...,1982,115,Family,7.8,Steven Spielberg,Henry Thomas,372490,435110554.0,91.0
568,Nosferatu ...,1922,94,Fantasy,7.9,F.W. Murnau,Max Schreck,88794,445151978.0,
568,Nosferatu ...,1922,94,Fantasy,7.9,F.W. Murnau,Max Schreck,88794,445151978.0,
309,The Third Man ...,1949,104,Film-Noir,8.1,Carol Reed,Orson Welles,158731,449191.0,97.0
309,The Third Man ...,1949,104,Film-Noir,8.1,Carol Reed,Orson Welles,158731,449191.0,97.0
844,Halloween ...,1978,91,Horror,7.7,John Carpenter,Donald Pleasence,233106,47000000.0,87.0
844,Halloween ...,1978,91,Horror,7.7,John Carpenter,Donald Pleasence,233106,47000000.0,87.0
959,Dark City ...,1998,100,Mystery,7.6,Alex Proyas,Rufus Sewell,187927,14378331.0,66.0
393,Twelve Monkeys ...,1995,129,Mystery,8.0,Terry Gilliam,Bruce Willis,578443,57141459.0,74.0
700,Wait Until Dark ...,1967,108,Thriller,7.8,Terence Young,Audrey Hepburn,27733,17550741.0,81.0
700,Wait Until Dark ...,1967,108,Thriller,7.8,Terence Young,Audrey Hepburn,27733,17550741.0,81.0
48,Once Upon a Time in the West ...,1968,165,Western,8.5,Sergio Leone,Henry Fonda,302844,5321508.0,80.0
48,Once Upon a Time in the West ...,1968,165,Western,8.5,Sergio Leone,Henry Fonda,302844,5321508.0,80.0

#### 8. nunique

In [29]:
genres.nunique()

,Series_Title,Released_Year,Runtime,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
Genre,,,,,,,,,
Action,172,61,78,15,123,121,172,172,51
Adventure,72,49,58,10,59,59,72,72,34
Animation,82,35,41,11,51,77,82,82,30
Biography,88,44,56,13,76,72,88,88,41
Comedy,155,72,70,11,113,133,155,155,45
Crime,106,56,65,14,86,85,107,107,40
Drama,289,83,95,14,211,250,288,287,53
Family,2,2,2,1,2,2,2,2,2
Fantasy,2,2,2,2,2,2,2,2,1
Film-Noir,3,3,3,3,3,3,3,3,3
Horror,11,11,10,8,10,11,11,11,9
Mystery,12,11,10,8,10,11,12,12,8
Thriller,1,1,1,1,1,1,1,1,1
Western,4,4,4,4,2,2,4,4,4

# **Agg method**

In [30]:
# agg method
# passing dict
genres.agg(
    {
        'Runtime':'mean',
        'IMDB_Rating':'mean',
        'No_of_Votes':'sum',
        'Gross':'sum',
        'Metascore':'min'
    }
)

              Runtime  IMDB_Rating  No_of_Votes         Gross   Metascore
Genre
Action     129.046512     7.949419     72282412  3.263226e+10
Adventure  134.111111     7.937500     22576163  9.496922e+09
Animation   99.585366     7.930488     21978630  1.463147e+10
Biography  136.022727     7.938636     24006844  8.276358e+09
Comedy     112.129032     7.901290     27620327  1.566387e+10
Crime      126.392523     8.016822     33533615  8.452632e+09
Drama      124.737024     7.957439     61367304  3.540997e+10
Family     107.500000     7.800000       551221  4.391106e+08        67.0
Fantasy     85.000000     8.000000       146222  7.827267e+08
Film-Noir  104.000000     7.966667       367215  1.259105e+08        94.0
Horror     102.090909     7.909091      3742556  1.034649e+09        46.0
Mystery    119.083333     7.975000      4203004  1.256417e+09
Thriller   108.000000     7.800000        27733  1.755074e+07        81.0
Western    148.250000     8.350000      1289665  5.822151e+07        69.0

In [31]:
# Passing list in dictionary
genres.agg(
    {
        'Runtime':['min','mean'],
        'IMDB_Rating':'mean',
        'No_of_Votes':['sum','max'],
        'Gross':'sum',
        'Metascore':'min'
    }
)

          Runtime             IMDB_Rating No_of_Votes                  Gross  \
              min        mean        mean         sum      max           sum
Genre
Action         45  129.046512    7.949419    72282412  2303232  3.263226e+10
Adventure      88  134.111111    7.937500    22576163  1512360  9.496922e+09
Animation      71   99.585366    7.930488    21978630   999790  1.463147e+10
Biography      93  136.022727    7.938636    24006844  1213505  8.276358e+09
Comedy         68  112.129032    7.901290    27620327   939631  1.566387e+10
Crime          80  126.392523    8.016822    33533615  1826188  8.452632e+09
Drama          64  124.737024    7.957439    61367304  2343110  3.540997e+10
Family        100  107.500000    7.800000      551221   372490  4.391106e+08
Fantasy        76   85.000000    8.000000      146222    88794  7.827267e+08
Film-Noir     100  104.000000    7.966667      367215   158731  1.259105e+08
Horror         71  102.090909    7.909091     3742556   787806  1.034649e+09
Mystery        96  119.083333    7.975000     4203004  1129894  1.256417e+09
Thriller      108  108.000000    7.800000       27733    27733  1.755074e+07
Western       132  148.250000    8.350000     1289665   688390  5.822151e+07

            Metascore
                  min
Genre
Action
Adventure
Animation
Biography
Comedy
Crime
Drama
Family           67.0
Fantasy
Film-Noir        94.0
Horror           46.0
Mystery
Thriller         81.0
Western          69.0

# **looping on groups**

In [32]:
# highest rated movie in each genre
dfs = []

for group, data in genres:
    dfs.append(
        data[data["IMDB_Rating"] == data["IMDB_Rating"].max()]
    )

df = pd.concat(dfs)
df

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
2,The Dark Knight ...,2008,152,Action,9.0,Christopher Nolan,Christian Bale,2303232,534858444.0,84.0
21,Interstellar ...,2014,169,Adventure,8.6,Christopher Nolan,Matthew McConaughey,1512360,188020017.0,74.0
23,Sen to Chihiro no kamikakushi ...,2001,125,Animation,8.6,Hayao Miyazaki,Daveigh Chase,651376,10055859.0,96.0
7,Schindler's List ...,1993,195,Biography,8.9,Steven Spielberg,Liam Neeson,1213505,96898818.0,94.0
19,Gisaengchung ...,2019,132,Comedy,8.6,Bong Joon Ho,Kang-ho Song,552778,53367844.0,96.0
26,La vita è bella ...,1997,116,Comedy,8.6,Roberto Benigni,Roberto Benigni,623629,57598247.0,59.0
1,The Godfather ...,1972,175,Crime,9.2,Francis Ford Coppola,Marlon Brando,1620367,134966411.0,100.0
0,The Shawshank Redemption ...,1994,142,Drama,9.3,Frank Darabont,Tim Robbins,2343110,28341469.0,80.0
688,E.T. the Extra-Terrestrial ...,1982,115,Family,7.8,Steven Spielberg,Henry Thomas,372490,435110554.0,91.0
698,Willy Wonka & the Chocolate Factory ...,1971,100,Family,7.8,Mel Stuart,Gene Wilder,178731,4000000.0,67.0
321,Das Cabinet des Dr. Caligari ...,1920,76,Fantasy,8.1,Robert Wiene,Werner Krauss,57428,337574718.0,
309,The Third Man ...,1949,104,Film-Noir,8.1,Carol Reed,Orson Welles,158731,449191.0,97.0
49,Psycho ...,1960,109,Horror,8.5,Alfred Hitchcock,Anthony Perkins,604211,32000000.0,97.0
69,Memento ...,2000,113,Mystery,8.4,Christopher Nolan,Guy Pearce,1125712,25544867.0,80.0
81,Rear Window ...,1954,112,Mystery,8.4,Alfred Hitchcock,James Stewart,444074,36764313.0,100.0
700,Wait Until Dark ...,1967,108,Thriller,7.8,Terence Young,Audrey Hepburn,27733,17550741.0,81.0
12,"Il buono, il brutto, il cattivo ...",1966,161,Western,8.8,Sergio Leone,Clint Eastwood,688390,6100000.0,90.0

In [33]:
# second highest gross in each genre
dfl = []

for group, data in movies.groupby("Genre"):
    data = data.sort_values(by="Gross", ascending=False)
    if len(data) > 1:
        dfl.append(data.iloc[1])

df = pd.DataFrame(dfl)
df

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
177,Sholay ...,1975,204,Action,8.2,Ramesh Sippy,Sanjeev Kumar,51284,932069480.0,
273,Fitzcarraldo ...,1982,158,Adventure,8.1,Werner Herzog,Klaus Kinski,31595,616558047.0,
822,Kurenai no buta ...,1992,94,Animation,7.7,Hayao Miyazaki,Shûichirô Moriyama,77798,871544815.0,83.0
54,Ayla: The Daughter of War ...,2017,125,Biography,8.4,Can Ulkay,Erdem Can,34112,679278040.0,
538,Amarcord ...,1973,123,Comedy,7.9,Federico Fellini,Magali Noël,39897,882861253.0,
163,Eskiya ...,1996,128,Crime,8.2,Yavuz Turgul,Sener Sen,64118,764480450.0,
872,The Day the Earth Stood Still ...,1951,92,Drama,7.7,Robert Wise,Michael Rennie,76315,895071115.0,
698,Willy Wonka & the Chocolate Factory ...,1971,100,Family,7.8,Mel Stuart,Gene Wilder,178731,4000000.0,67.0
321,Das Cabinet des Dr. Caligari ...,1920,76,Fantasy,8.1,Robert Wiene,Werner Krauss,57428,337574718.0,
456,The Maltese Falcon ...,1941,100,Film-Noir,8.0,John Huston,Humphrey Bogart,148928,2108060.0,96.0
419,The Exorcist ...,1973,122,Horror,8.0,William Friedkin,Ellen Burstyn,362393,232906145.0,81.0
829,Spoorloos ...,1988,107,Mystery,7.7,George Sluizer,Bernard-Pierre Donnadieu,33982,367916835.0,
115,Per qualche dollaro in più ...,1965,132,Western,8.3,Sergio Leone,Clint Eastwood,232772,15000000.0,74.0

In [34]:
movies.columns

Index(['Series_Title', 'Released_Year', 'Runtime', 'Genre', 'IMDB_Rating',
       'Director', 'Star1', 'No_of_Votes', 'Gross', 'Metascore'],
      dtype='object')

# Apply

In [35]:
# split (apply) combine
# apply -> builtin function

genres.apply(min)

/tmp/ipykernel_14180/3127779659.py:4: FutureWarning: The provided callable <built-in function min> is currently using np.minimum.reduce. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string np.minimum.reduce instead.
  genres.apply(min)
/tmp/ipykernel_14180/3127779659.py:4: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  genres.apply(min)

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
Genre,,,,,,,,,,
Action,300 ...,1924,45,Action,7.6,Abhishek Chaubey,Aamir Khan,25312,3296.0,
Adventure,2001: A Space Odyssey ...,1925,88,Adventure,7.6,Akira Kurosawa,Aamir Khan,29999,61001.0,
Animation,Akira ...,1940,71,Animation,7.6,Adam Elliot,Adrian Molina,25229,128985.0,
Biography,12 Years a Slave ...,1928,93,Biography,7.6,Adam McKay,Adrien Brody,27254,21877.0,
Comedy,(500) Days of Summer ...,1921,68,Comedy,7.6,Alejandro G. Iñárritu,Aamir Khan,26337,1305.0,
Crime,12 Angry Men ...,1931,80,Crime,7.6,Akira Kurosawa,Ajay Devgn,27712,6013.0,
Drama,1917 ...,1925,64,Drama,7.6,Aamir Khan,Abhay Deol,25088,3600.0,
Family,E.T. the Extra-Terrestrial ...,1971,100,Family,7.8,Mel Stuart,Gene Wilder,178731,4000000.0,67.0
Fantasy,Das Cabinet des Dr. Caligari ...,1920,76,Fantasy,7.9,F.W. Murnau,Max Schreck,57428,337574718.0,
Film-Noir,Shadow of a Doubt ...,1941,100,Film-Noir,7.8,Alfred Hitchcock,Humphrey Bogart,59556,449191.0,94.0
Horror,Alien ...,1933,71,Horror,7.6,Alejandro Amenábar,Anthony Perkins,27007,89029.0,46.0
Mystery,Dark City ...,1938,96,Mystery,7.6,Alex Proyas,Bernard-Pierre Donnadieu,33982,1035953.0,
Thriller,Wait Until Dark ...,1967,108,Thriller,7.8,Terence Young,Audrey Hepburn,27733,17550741.0,81.0
Western,"Il buono, il brutto, il cattivo ...",1965,132,Western,7.8,Clint Eastwood,Clint Eastwood,65659,5321508.0,69.0

In [36]:
# find number of movies starting with A for each group

def foo(group):
  return group['Series_Title'].str.startswith('A').sum()

In [37]:
genres.apply(foo)

/tmp/ipykernel_14180/2904676014.py:1: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  genres.apply(foo)

Genre
Action       10
Adventure     2
Animation     2
Biography     9
Comedy       14
Crime         4
Drama        21
Family        0
Fantasy       0
Film-Noir     0
Horror        1
Mystery       0
Thriller      0
Western       0
dtype: int64

In [38]:
# find ranking of each movie in the group according to IMDB score

def rank_movie(group):
  group['genre_rank'] = group['IMDB_Rating'].rank(ascending=False)
  return group

In [39]:
genres.apply(rank_movie)

/tmp/ipykernel_14180/2409710219.py:1: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  genres.apply(rank_movie)

                                                   Series_Title  \
Genre
Action   2    The Dark Knight                               ...
         5    The Lord of the Rings: The Return of the King ...
         8    Inception                                     ...
         10   The Lord of the Rings: The Fellowship of the R...
         13   The Lord of the Rings: The Two Towers         ...
...                                                         ...
Thriller 700  Wait Until Dark                               ...
Western  12   Il buono, il brutto, il cattivo               ...
         48   Once Upon a Time in the West                  ...
         115  Per qualche dollaro in più                    ...
         691  The Outlaw Josey Wales                        ...

               Released_Year  Runtime     Genre  IMDB_Rating  \
Genre
Action   2     2008               152    Action          9.0
         5     2003               201    Action          8.9
         8     2010               148    Action          8.8
         10    2001               178    Action          8.8
         13    2002               179    Action          8.7
...                      ...      ...       ...          ...
Thriller 700   1967               108  Thriller          7.8
Western  12    1966               161   Western          8.8
         48    1968               165   Western          8.5
         115   1965               132   Western          8.3
         691   1976               135   Western          7.8

                                       Director                       Star1  \
Genre
Action   2     Christopher Nolan                  Christian Bale
         5     Peter Jackson                      Elijah Wood
         8     Christopher Nolan                  Leonardo DiCaprio
         10    Peter Jackson                      Elijah Wood
         13    Peter Jackson                      Elijah Wood
...                                         ...                         ...
Thriller 700   Terence Young                      Audrey Hepburn
Western  12    Sergio Leone                       Clint Eastwood
         48    Sergio Leone                       Henry Fonda
         115   Sergio Leone                       Clint Eastwood
         691   Clint Eastwood                     Clint Eastwood

              No_of_Votes        Gross   Metascore  genre_rank
Genre
Action   2        2303232  534858444.0        84.0         1.0
         5        1642758  377845905.0        94.0         2.0
         8        2067042  292576195.0        74.0         3.5
         10       1661481  315544750.0        92.0         3.5
         13       1485555  342551365.0        87.0         6.0
...                   ...          ...         ...         ...
Thriller 700        27733   17550741.0        81.0         1.0
Western  12        688390    6100000.0        90.0         1.0
         48        302844    5321508.0        80.0         2.0
         115       232772   15000000.0        74.0         3.0
         691        65659   31800000.0        69.0         4.0

[1000 rows x 11 columns]

In [40]:
# imdb rating 9
# min rating 7.6
# max rating 9
9-7.6
9-7.6

1.4000000000000004

In [41]:
genres["IMDB_Rating"].max()

Genre
Action       9.0
Adventure    8.6
Animation    8.6
Biography    8.9
Comedy       8.6
Crime        9.2
Drama        9.3
Family       7.8
Fantasy      8.1
Film-Noir    8.1
Horror       8.5
Mystery      8.4
Thriller     7.8
Western      8.8
Name: IMDB_Rating, dtype: float64

In [42]:
# find normalized IMDB rating group wise

def normal(group):
  group['norm_rating'] = (group['IMDB_Rating'] - group['IMDB_Rating'].min())/(group['IMDB_Rating'].max() - group['IMDB_Rating'].min())
  return group

genres.apply(normal)

/tmp/ipykernel_14180/2908049479.py:7: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  genres.apply(normal)

                                                   Series_Title  \
Genre
Action   2    The Dark Knight                               ...
         5    The Lord of the Rings: The Return of the King ...
         8    Inception                                     ...
         10   The Lord of the Rings: The Fellowship of the R...
         13   The Lord of the Rings: The Two Towers         ...
...                                                         ...
Thriller 700  Wait Until Dark                               ...
Western  12   Il buono, il brutto, il cattivo               ...
         48   Once Upon a Time in the West                  ...
         115  Per qualche dollaro in più                    ...
         691  The Outlaw Josey Wales                        ...

               Released_Year  Runtime     Genre  IMDB_Rating  \
Genre
Action   2     2008               152    Action          9.0
         5     2003               201    Action          8.9
         8     2010               148    Action          8.8
         10    2001               178    Action          8.8
         13    2002               179    Action          8.7
...                      ...      ...       ...          ...
Thriller 700   1967               108  Thriller          7.8
Western  12    1966               161   Western          8.8
         48    1968               165   Western          8.5
         115   1965               132   Western          8.3
         691   1976               135   Western          7.8

                                       Director                       Star1  \
Genre
Action   2     Christopher Nolan                  Christian Bale
         5     Peter Jackson                      Elijah Wood
         8     Christopher Nolan                  Leonardo DiCaprio
         10    Peter Jackson                      Elijah Wood
         13    Peter Jackson                      Elijah Wood
...                                         ...                         ...
Thriller 700   Terence Young                      Audrey Hepburn
Western  12    Sergio Leone                       Clint Eastwood
         48    Sergio Leone                       Henry Fonda
         115   Sergio Leone                       Clint Eastwood
         691   Clint Eastwood                     Clint Eastwood

              No_of_Votes        Gross   Metascore  norm_rating
Genre
Action   2        2303232  534858444.0        84.0     1.000000
         5        1642758  377845905.0        94.0     0.928571
         8        2067042  292576195.0        74.0     0.857143
         10       1661481  315544750.0        92.0     0.857143
         13       1485555  342551365.0        87.0     0.785714
...                   ...          ...         ...          ...
Thriller 700        27733   17550741.0        81.0          NaN
Western  12        688390    6100000.0        90.0     1.000000
         48        302844    5321508.0        80.0     0.700000
         115       232772   15000000.0        74.0     0.500000
         691        65659   31800000.0        69.0     0.000000

[1000 rows x 11 columns]

In [43]:
# groupby on multiple cols
duo = movies.groupby(['Director','Star1'])
duo
# size
# duo.size()
# get_group
# duo.get_group(('Aamir Khan','Amole Gupte'))

In [44]:
# find the most earning actor->director combo
duo['Gross'].sum().sort_values(ascending=False).head(1)

Director                          Star1
Akira Kurosawa                    Toshirô Mifune               2.999877e+09
Name: Gross, dtype: float64

In [45]:
# find the best(in-terms of metascore(avg)) actor->genre combo
movies.groupby(['Star1','Genre'])['Metascore'].mean().reset_index().sort_values('Metascore',ascending=False).head(1)

TypeError: agg function failed [how->mean,dtype->object]

In [ ]:
# agg on multiple groupby
duo.agg(['min','max','mean'])

                                   Runtime             IMDB_Rating            \
                                       min  max   mean         min  max mean
Director            Star1
Aamir Khan          Amole Gupte        165  165  165.0         8.4  8.4  8.4
Aaron Sorkin        Eddie Redmayne     129  129  129.0         7.8  7.8  7.8
Abdellatif Kechiche Léa Seydoux        180  180  180.0         7.7  7.7  7.7
Abhishek Chaubey    Shahid Kapoor      148  148  148.0         7.8  7.8  7.8
Abhishek Kapoor     Amit Sadh          130  130  130.0         7.7  7.7  7.7
...                                    ...  ...    ...         ...  ...  ...
Zaza Urushadze      Lembit Ulfsak       87   87   87.0         8.2  8.2  8.2
Zoya Akhtar         Hrithik Roshan     155  155  155.0         8.1  8.1  8.1
                    Vijay Varma        154  154  154.0         8.0  8.0  8.0
Çagan Irmak         Çetin Tekindor     112  112  112.0         8.3  8.3  8.3
Ömer Faruk Sorak    Cem Yilmaz         127  127  127.0         8.0  8.0  8.0

                                   No_of_Votes                          Gross  \
                                           min     max      mean          min
Director            Star1
Aamir Khan          Amole Gupte         168895  168895  168895.0    1223869.0
Aaron Sorkin        Eddie Redmayne       89896   89896   89896.0  853090410.0
Abdellatif Kechiche Léa Seydoux         138741  138741  138741.0    2199675.0
Abhishek Chaubey    Shahid Kapoor        27175   27175   27175.0  218428303.0
Abhishek Kapoor     Amit Sadh            32628   32628   32628.0    1122527.0
...                                        ...     ...       ...          ...
Zaza Urushadze      Lembit Ulfsak        40382   40382   40382.0     144501.0
Zoya Akhtar         Hrithik Roshan       67927   67927   67927.0    3108485.0
                    Vijay Varma          31886   31886   31886.0    5566534.0
Çagan Irmak         Çetin Tekindor       78925   78925   78925.0  461855363.0
Ömer Faruk Sorak    Cem Yilmaz           56960   56960   56960.0  196206077.0

                                                             Metascore        \
                                            max         mean       min   max
Director            Star1
Aamir Khan          Amole Gupte       1223869.0    1223869.0       NaN   NaN
Aaron Sorkin        Eddie Redmayne  853090410.0  853090410.0      77.0  77.0
Abdellatif Kechiche Léa Seydoux       2199675.0    2199675.0      89.0  89.0
Abhishek Chaubey    Shahid Kapoor   218428303.0  218428303.0       NaN   NaN
Abhishek Kapoor     Amit Sadh         1122527.0    1122527.0      40.0  40.0
...                                         ...          ...       ...   ...
Zaza Urushadze      Lembit Ulfsak      144501.0     144501.0      73.0  73.0
Zoya Akhtar         Hrithik Roshan    3108485.0    3108485.0       NaN   NaN
                    Vijay Varma       5566534.0    5566534.0      65.0  65.0
Çagan Irmak         Çetin Tekindor  461855363.0  461855363.0       NaN   NaN
Ömer Faruk Sorak    Cem Yilmaz      196206077.0  196206077.0       NaN   NaN


                                    mean
Director            Star1
Aamir Khan          Amole Gupte      NaN
Aaron Sorkin        Eddie Redmayne  77.0
Abdellatif Kechiche Léa Seydoux     89.0
Abhishek Chaubey    Shahid Kapoor    NaN
Abhishek Kapoor     Amit Sadh       40.0
...                                  ...
Zaza Urushadze      Lembit Ulfsak   73.0
Zoya Akhtar         Hrithik Roshan   NaN
                    Vijay Varma     65.0
Çagan Irmak         Çetin Tekindor   NaN
Ömer Faruk Sorak    Cem Yilmaz       NaN

[898 rows x 15 columns]

### Excercise

In [ ]:
ipl = pd.read_csv('/content/deliveries.csv')
ipl.head()

,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,...,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs,player_dismissed,dismissal_kind,fielder
0,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,1,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
1,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,2,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
2,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,3,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
3,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,4,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
4,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,5,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,2,2,NaN,NaN,NaN

In [ ]:
ipl.shape

(179078, 21)

In [ ]:
# find the top 10 batsman in terms of runs
ipl.groupby('batsman')['batsman_runs'].sum().sort_values(ascending=False).head(10)

batsman
V Kohli           5434
SK Raina          5415
RG Sharma         4914
DA Warner         4741
S Dhawan          4632
CH Gayle          4560
MS Dhoni          4477
RV Uthappa        4446
AB de Villiers    4428
G Gambhir         4223
Name: batsman_runs, dtype: int64

In [ ]:
# find the batsman with max no of sixes
six = ipl[ipl['batsman_runs'] == 6]

six.groupby('batsman')['batsman'].count().sort_values(ascending=False).head(1).index[0]

'CH Gayle'

In [ ]:
# find batsman with most number of 4's and 6's in last 5 overs
temp_df = ipl[ipl['over'] > 15]
temp_df = temp_df[(temp_df['batsman_runs'] == 4) | (temp_df['batsman_runs'] == 6)]
temp_df.groupby('batsman')['batsman'].count().sort_values(ascending=False).head(1).index[0]

'MS Dhoni'

In [ ]:
# find V Kohli's record against all teams
temp_df = ipl[ipl['batsman'] == 'V Kohli']

temp_df.groupby('bowling_team')['batsman_runs'].sum().reset_index()

               bowling_team  batsman_runs
0       Chennai Super Kings           749
1           Deccan Chargers           306
2            Delhi Capitals            66
3          Delhi Daredevils           763
4             Gujarat Lions           283
5           Kings XI Punjab           636
6      Kochi Tuskers Kerala            50
7     Kolkata Knight Riders           675
8            Mumbai Indians           628
9             Pune Warriors           128
10         Rajasthan Royals           370
11   Rising Pune Supergiant            83
12  Rising Pune Supergiants           188
13      Sunrisers Hyderabad           509

In [ ]:
# Create a function that can return the highest score of any batsman
temp_df = ipl[ipl['batsman'] == 'V Kohli']
temp_df.groupby('match_id')['batsman_runs'].sum().sort_values(ascending=False).head(1).values[0]

113

In [ ]:
def highest(batsman):
  temp_df = ipl[ipl['batsman'] == batsman]
  return temp_df.groupby('match_id')['batsman_runs'].sum().sort_values(ascending=False).head(1).values[0]

In [ ]:
highest('DA Warner')

126